using System;

namespace VelorenPort.Network {
    /// <summary>
    /// Event generated by a <see cref="Participant"/> when channels are created
    /// or deleted. Expressed as a discriminated union to mirror the Rust enum
    /// semantics.
    /// </summary>
    [Serializable]
    public abstract record ParticipantEvent {
        public sealed record ChannelCreated(ConnectAddr Address) : ParticipantEvent;
        public sealed record ChannelDeleted(ConnectAddr Address) : ParticipantEvent;
    }
}
