using System;

namespace VelorenPort.Server.Events {
    /// <summary>
    /// Enumeration of server events. Mirrors <c>server/src/events/event_types.rs</c>
    /// but is condensed into a single enum without separate structures.
    /// </summary>
    public enum EventType
    {
        ClientDisconnect,
        ClientDisconnectWithoutPersistence,
        Chat,
        Command,
        CreateSpecialEntity,
        CreateNpc,
        CreateShip,
        CreateItemDrop,
        CreateObject,
        Explosion,
        Bonk,
        HealthChange,
        Kill,
        HelpDowned,
        Downed,
        PoiseChange,
        Delete,
        Destroy,
        InventoryManip,
        GroupManip,
        Respawn,
        Shoot,
        Throw,
        Shockwave,
        Knockback,
        LandOnGround,
        SetLantern,
        NpcInteract,
        Dialogue,
        InviteResponse,
        InitiateInvite,
        ProcessTradeAction,
        Mount,
        SetPetStay,
        Possess,
        InitializeCharacter,
        InitializeSpectator,
        UpdateCharacterData,
        ExitIngame,
        Aura,
        Buff,
        EnergyChange,
        ComboChange,
        ParryHook,
        RequestSiteInfo,
        MineBlock,
        TeleportTo,
        Sound,
        CreateSprite,
        TamePet,
        EntityAttackedHook,
        ChangeAbility,
        UpdateMapMarker,
        MakeAdmin,
        DeleteCharacter,
        ChangeStance,
        ChangeBody,
        RemoveLightEmitter,
        TeleportToPosition,
        StartTeleporting,
        ToggleSpriteLight,
        Transform,
        StartInteraction,
        RequestPlugins,
        CreateAuraEntity,
        RegrowHead,
        SetBattleMode,
    }
}
